### ISSUE TITLE
Looks good, just a couple of things....

### ISSUE THREAD

**Issue by AlisaMarie** [PukaFish/PukaFish.github.io#1]
Crop image, make your face bigger
center about section (picture above and words below)
make text bigger
might be fun to change the link colours
Resume its own page instead of pdf (itll look a bit better that way and you can like to the pdf in it as well)

keep working on it! looking good honey!

**Comment by PukaFish** [comment]
Hello AlisaMarie,
Thank you so much for your feedback. I agree my current picture features more of my scenery rather than a focus on myself and it can be hard to see my text, especially on mobile devices. I'll be graciously taking your advice concerning, profile image, centering of section, and making the text bigger. I currently replaced the light blue link text color with a darker text to match the overall text theme, but I will see in the future if there is room to make it more creative. For the resume advice, I will be sure to take that advice in the future as there are still more imperative functions in the site that needs information filled out. 
Thank you for your time and interest!
